version: '3.8'

services:
  # Hadoop NameNode
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./data:/data
    environment:
      - CLUSTER_NAME=terraflow
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    env_file:
      - ./docker/hadoop.env
    networks:
      - terraflow_network

  # Hadoop DataNode
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    ports:
      - "9864:9864"
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
      - ./data:/data
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    env_file:
      - ./docker/hadoop.env
    networks:
      - terraflow_network
    depends_on:
      - namenode

  # Spark Master
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    restart: always
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./data:/data
      - ./notebooks:/notebooks
      - ./src:/src
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      # Optional stability defaults
      - SPARK_MASTER_OPTS=-Dspark.deploy.defaultCores=2
    networks:
      - terraflow_network
    depends_on:
      - namenode

  # Spark Worker 1
  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./data:/data
      - ./notebooks:/notebooks
      - ./src:/src
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2

      # IMPORTANT: give the worker enough memory for executors
      # Your notebook was requesting 2g; set worker >= 3G to allow overhead.
      - SPARK_WORKER_MEMORY=3G

      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000

      # Optional stability defaults (reduce "executor lost" / heartbeat issues)
      - SPARK_WORKER_OPTS=-Dspark.worker.cleanup.enabled=true -Dspark.worker.cleanup.interval=1800
    networks:
      - terraflow_network
    depends_on:
      - spark-master

  # Jupyter Notebook with PySpark (Spark driver)
  jupyter:
    image: jupyter/pyspark-notebook:spark-3.3.2
    container_name: jupyter-pyspark
    restart: always
    ports:
      - "8888:8888"
      - "4040:4040"
      - "4041:4041"
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks
      - ./data:/home/jovyan/work/data
      - ./src:/home/jovyan/work/src
      - ./dashboard:/home/jovyan/work/dashboard
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes

      # Spark connection
      - SPARK_MASTER=spark://spark-master:7077

      # Make sure the driver is reachable by executors:
      # Use the *service/container name* on the docker network.
      # (Executors will connect back to this.)
      - SPARK_DRIVER_HOST=jupyter-pyspark
      - SPARK_DRIVER_BIND_ADDRESS=0.0.0.0

      # Safer submit args (do not force driver ports)
      - PYSPARK_SUBMIT_ARGS=--master spark://spark-master:7077 --conf spark.driver.host=jupyter-pyspark --conf spark.driver.bindAddress=0.0.0.0 --conf spark.network.timeout=600s --conf spark.executor.heartbeatInterval=60s pyspark-shell
    user: root
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
    networks:
      - terraflow_network
    depends_on:
      - namenode
      - spark-master
      - spark-worker-1

volumes:
  hadoop_namenode:
  hadoop_datanode:

networks:
  terraflow_network:
    driver: bridge
